name = "Cobblemon Sharp"
author = "valentimarco & contributors"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51b85058bde34056e0605bb9578d0531e9e04b0a8e8dd16abaec82f44fe2751a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/paxi/datapacks"
