name = "Cobblemon Sharp"
author = "valentimarco & contributors"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0492aa9c59fbfcd76b10140f72698293efb4ac2df5c34a99f0feb092a60d644b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "./config/paxi/datapacks"
